services:
  - type: web
    name: ecommerce-api
    env: python
    buildCommand: pip install --no-cache-dir --only-binary :all: fastapi==0.89.1 uvicorn==0.22.0 motor==3.1.2 pymongo==4.13.0 python-dotenv==1.0.0 typing-extensions==4.8.0
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URL
        sync: false # This means you'll need to set it manually in the Render dashboard 